# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
